---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Darwin.yml
  when: "ansible_os_family == 'Darwin'"
  static: no

- name: Place docker client config file.
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
  notify: restart docker
