---
- name: Ensure helper packages are installed.
  yum:
    name: [ yum-utils, device-mapper-persistent-data, lvm2 ]
    state: latest

- name: Add docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo

- name: Ensure latest docker is installed.
  yum:
    name: docker-ce
    state: present
  when: docker_version == 'latest'

- name: Ensure specified docker is installed.
  yum:
    name: docker-ce-{{ docker_version }}
    state: present
  when: docker_version != 'latest'
  
- name: Ensure docker is started and enabled to start at boot.
  service: name=docker state=started enabled=yes
  when: ansible_connection != 'docker'
